CREATE TABLE courses (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    active BIT(1) NOT NULL,
    category ENUM('IA', 'FULLSTACK', 'ENGLISHFORDEVELOPERS', 'TESTING') NOT NULL,
    name VARCHAR(255) NOT NULL
);