CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    lastname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    enabled BIT(1) NOT NULL,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('ADMINISTRATOR', 'USER', 'EXPECTER') NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE
);